---
- name: 웹 서비스 배포
  hosts: 도커호스트
  become: true
  
  tasks:
    - name: nginx 컨테이너 실행
      docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: on-failure
        restart_retries: 3
        networks:
          - name: web
        deploy:
          replicas: 2
          resources:
            limits:
              cpus: '1'
              memory: '32M'
          placement:
            constraints: [node.role != manager]

    - name: proxy 컨테이너 실행
      docker_container:
        name: proxy
        image: dockercloud/haproxy
        state: started
        restart_policy: on-failure
        restart_retries: 3
        networks:
          - name: web
        ports:
          - "8000:8000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
          mode: global
          placement:
            constraints: [node.role == manager]

    - name: 웹 네트워크 생성
      docker_network:
        name: web
        state: present
        external: yes
